
package org.sid;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Convert_USD_to_MAD")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Convert_USD_to_MAD", targetNamespace = "http://ws/", className = "org.sid.ConvertUSDToMAD")
    @ResponseWrapper(localName = "Convert_USD_to_MADResponse", targetNamespace = "http://ws/", className = "org.sid.ConvertUSDToMADResponse")
    @Action(input = "http://ws/BankService/Convert_USD_to_MADRequest", output = "http://ws/BankService/Convert_USD_to_MADResponse")
    public double convertUSDToMAD(
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @param id
     * @return
     *     returns org.sid.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws/", className = "org.sid.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws/", className = "org.sid.GetAccountResponse")
    @Action(input = "http://ws/BankService/getAccountRequest", output = "http://ws/BankService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "Id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<org.sid.Account>
     */
    @WebMethod(operationName = "AccountsList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AccountsList", targetNamespace = "http://ws/", className = "org.sid.AccountsList")
    @ResponseWrapper(localName = "AccountsListResponse", targetNamespace = "http://ws/", className = "org.sid.AccountsListResponse")
    @Action(input = "http://ws/BankService/AccountsListRequest", output = "http://ws/BankService/AccountsListResponse")
    public List<Account> accountsList();

}
