//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="BankServiceReference.BankService")]
    public interface BankService
    {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankService/Convert_USD_to_MADRequest", ReplyAction="http://ws/BankService/Convert_USD_to_MADResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BankServiceReference.Convert_USD_to_MADResponse Convert_USD_to_MAD(BankServiceReference.Convert_USD_to_MADRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankService/Convert_USD_to_MADRequest", ReplyAction="http://ws/BankService/Convert_USD_to_MADResponse")]
        System.Threading.Tasks.Task<BankServiceReference.Convert_USD_to_MADResponse> Convert_USD_to_MADAsync(BankServiceReference.Convert_USD_to_MADRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankService/getAccountRequest", ReplyAction="http://ws/BankService/getAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BankServiceReference.getAccountResponse getAccount(BankServiceReference.getAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankService/getAccountRequest", ReplyAction="http://ws/BankService/getAccountResponse")]
        System.Threading.Tasks.Task<BankServiceReference.getAccountResponse> getAccountAsync(BankServiceReference.getAccountRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankService/AccountsListRequest", ReplyAction="http://ws/BankService/AccountsListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BankServiceReference.AccountsListResponse AccountsList(BankServiceReference.AccountsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankService/AccountsListRequest", ReplyAction="http://ws/BankService/AccountsListResponse")]
        System.Threading.Tasks.Task<BankServiceReference.AccountsListResponse> AccountsListAsync(BankServiceReference.AccountsListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Convert_USD_to_MAD", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class Convert_USD_to_MADRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double amount;
        
        public Convert_USD_to_MADRequest()
        {
        }
        
        public Convert_USD_to_MADRequest(double amount)
        {
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Convert_USD_to_MADResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class Convert_USD_to_MADResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public Convert_USD_to_MADResponse()
        {
        }
        
        public Convert_USD_to_MADResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class account
    {
        
        private int idField;
        
        private double balanceField;
        
        private System.DateTime creationDateField;
        
        private bool creationDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double Balance
        {
            get
            {
                return this.balanceField;
            }
            set
            {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime CreationDate
        {
            get
            {
                return this.creationDateField;
            }
            set
            {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreationDateSpecified
        {
            get
            {
                return this.creationDateFieldSpecified;
            }
            set
            {
                this.creationDateFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccount", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Id;
        
        public getAccountRequest()
        {
        }
        
        public getAccountRequest(int Id)
        {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BankServiceReference.account @return;
        
        public getAccountResponse()
        {
        }
        
        public getAccountResponse(BankServiceReference.account @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountsList", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class AccountsListRequest
    {
        
        public AccountsListRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountsListResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class AccountsListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BankServiceReference.account[] @return;
        
        public AccountsListResponse()
        {
        }
        
        public AccountsListResponse(BankServiceReference.account[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface BankServiceChannel : BankServiceReference.BankService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<BankServiceReference.BankService>, BankServiceReference.BankService
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BankServiceClient() : 
                base(BankServiceClient.GetDefaultBinding(), BankServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BankServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BankServiceClient.GetBindingForEndpoint(endpointConfiguration), BankServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BankServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BankServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankServiceReference.Convert_USD_to_MADResponse BankServiceReference.BankService.Convert_USD_to_MAD(BankServiceReference.Convert_USD_to_MADRequest request)
        {
            return base.Channel.Convert_USD_to_MAD(request);
        }
        
        public double Convert_USD_to_MAD(double amount)
        {
            BankServiceReference.Convert_USD_to_MADRequest inValue = new BankServiceReference.Convert_USD_to_MADRequest();
            inValue.amount = amount;
            BankServiceReference.Convert_USD_to_MADResponse retVal = ((BankServiceReference.BankService)(this)).Convert_USD_to_MAD(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankServiceReference.Convert_USD_to_MADResponse> BankServiceReference.BankService.Convert_USD_to_MADAsync(BankServiceReference.Convert_USD_to_MADRequest request)
        {
            return base.Channel.Convert_USD_to_MADAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceReference.Convert_USD_to_MADResponse> Convert_USD_to_MADAsync(double amount)
        {
            BankServiceReference.Convert_USD_to_MADRequest inValue = new BankServiceReference.Convert_USD_to_MADRequest();
            inValue.amount = amount;
            return ((BankServiceReference.BankService)(this)).Convert_USD_to_MADAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankServiceReference.getAccountResponse BankServiceReference.BankService.getAccount(BankServiceReference.getAccountRequest request)
        {
            return base.Channel.getAccount(request);
        }
        
        public BankServiceReference.account getAccount(int Id)
        {
            BankServiceReference.getAccountRequest inValue = new BankServiceReference.getAccountRequest();
            inValue.Id = Id;
            BankServiceReference.getAccountResponse retVal = ((BankServiceReference.BankService)(this)).getAccount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankServiceReference.getAccountResponse> BankServiceReference.BankService.getAccountAsync(BankServiceReference.getAccountRequest request)
        {
            return base.Channel.getAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceReference.getAccountResponse> getAccountAsync(int Id)
        {
            BankServiceReference.getAccountRequest inValue = new BankServiceReference.getAccountRequest();
            inValue.Id = Id;
            return ((BankServiceReference.BankService)(this)).getAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankServiceReference.AccountsListResponse BankServiceReference.BankService.AccountsList(BankServiceReference.AccountsListRequest request)
        {
            return base.Channel.AccountsList(request);
        }
        
        public BankServiceReference.account[] AccountsList()
        {
            BankServiceReference.AccountsListRequest inValue = new BankServiceReference.AccountsListRequest();
            BankServiceReference.AccountsListResponse retVal = ((BankServiceReference.BankService)(this)).AccountsList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankServiceReference.AccountsListResponse> BankServiceReference.BankService.AccountsListAsync(BankServiceReference.AccountsListRequest request)
        {
            return base.Channel.AccountsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceReference.AccountsListResponse> AccountsListAsync()
        {
            BankServiceReference.AccountsListRequest inValue = new BankServiceReference.AccountsListRequest();
            return ((BankServiceReference.BankService)(this)).AccountsListAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BankServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BankServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8084/");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BankServiceClient.GetBindingForEndpoint(EndpointConfiguration.BankServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BankServiceClient.GetEndpointAddress(EndpointConfiguration.BankServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            BankServicePort,
        }
    }
}
