//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="BankServiceReference.BankService")]
    public interface BankService {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankService/Convert_USD_to_MADRequest", ReplyAction="http://ws/BankService/Convert_USD_to_MADResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADResponse Convert_USD_to_MAD(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankService/Convert_USD_to_MADRequest", ReplyAction="http://ws/BankService/Convert_USD_to_MADResponse")]
        System.Threading.Tasks.Task<soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADResponse> Convert_USD_to_MADAsync(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankService/getAccountRequest", ReplyAction="http://ws/BankService/getAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountResponse getAccount(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankService/getAccountRequest", ReplyAction="http://ws/BankService/getAccountResponse")]
        System.Threading.Tasks.Task<soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountResponse> getAccountAsync(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankService/AccountsListRequest", ReplyAction="http://ws/BankService/AccountsListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListResponse AccountsList(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankService/AccountsListRequest", ReplyAction="http://ws/BankService/AccountsListResponse")]
        System.Threading.Tasks.Task<soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListResponse> AccountsListAsync(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Convert_USD_to_MAD", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class Convert_USD_to_MADRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double amount;
        
        public Convert_USD_to_MADRequest() {
        }
        
        public Convert_USD_to_MADRequest(double amount) {
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Convert_USD_to_MADResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class Convert_USD_to_MADResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public Convert_USD_to_MADResponse() {
        }
        
        public Convert_USD_to_MADResponse(double @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class account : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private double balanceField;
        
        private System.DateTime creationDateField;
        
        private bool creationDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreationDateSpecified {
            get {
                return this.creationDateFieldSpecified;
            }
            set {
                this.creationDateFieldSpecified = value;
                this.RaisePropertyChanged("CreationDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccount", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Id;
        
        public getAccountRequest() {
        }
        
        public getAccountRequest(int Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.account @return;
        
        public getAccountResponse() {
        }
        
        public getAccountResponse(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.account @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountsList", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class AccountsListRequest {
        
        public AccountsListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountsListResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class AccountsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.account[] @return;
        
        public AccountsListResponse() {
        }
        
        public AccountsListResponse(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.account[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BankServiceChannel : soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService>, soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService {
        
        public BankServiceClient() {
        }
        
        public BankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADResponse soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService.Convert_USD_to_MAD(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADRequest request) {
            return base.Channel.Convert_USD_to_MAD(request);
        }
        
        public double Convert_USD_to_MAD(double amount) {
            soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADRequest inValue = new soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADRequest();
            inValue.amount = amount;
            soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADResponse retVal = ((soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService)(this)).Convert_USD_to_MAD(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADResponse> soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService.Convert_USD_to_MADAsync(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADRequest request) {
            return base.Channel.Convert_USD_to_MADAsync(request);
        }
        
        public System.Threading.Tasks.Task<soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADResponse> Convert_USD_to_MADAsync(double amount) {
            soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADRequest inValue = new soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.Convert_USD_to_MADRequest();
            inValue.amount = amount;
            return ((soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService)(this)).Convert_USD_to_MADAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountResponse soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService.getAccount(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountRequest request) {
            return base.Channel.getAccount(request);
        }
        
        public soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.account getAccount(int Id) {
            soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountRequest inValue = new soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountRequest();
            inValue.Id = Id;
            soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountResponse retVal = ((soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService)(this)).getAccount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountResponse> soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService.getAccountAsync(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountRequest request) {
            return base.Channel.getAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountResponse> getAccountAsync(int Id) {
            soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountRequest inValue = new soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.getAccountRequest();
            inValue.Id = Id;
            return ((soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService)(this)).getAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListResponse soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService.AccountsList(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListRequest request) {
            return base.Channel.AccountsList(request);
        }
        
        public soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.account[] AccountsList() {
            soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListRequest inValue = new soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListRequest();
            soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListResponse retVal = ((soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService)(this)).AccountsList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListResponse> soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService.AccountsListAsync(soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListRequest request) {
            return base.Channel.AccountsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListResponse> AccountsListAsync() {
            soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListRequest inValue = new soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.AccountsListRequest();
            return ((soap_ws_dotnet_csharp_app_windows_forms_client.BankServiceReference.BankService)(this)).AccountsListAsync(inValue);
        }
    }
}
